In [1]:
import tensorflow as tf
from tensorflow import keras
import tensorflow_datasets as tfds

In [2]:
(train_ds, val_ds, test_ds), metadata = tfds.load(
    'tf_flowers',
    split=['train[:80%]', 'train[80%:90%]', 'train[90%:]'],
    with_info=True,
    as_supervised=True,
)

In [3]:
samples = []
for data in train_ds.take(2):
    samples.append(data[0])

In [4]:
samples[0].shape, samples[1].shape

(TensorShape([333, 500, 3]), TensorShape([212, 320, 3]))

In [5]:
sample1 = tf.image.resize(samples[0], [180, 180])
sample2 = tf.image.resize(samples[1], [180, 180])
sample1.shape, sample2.shape

(TensorShape([180, 180, 3]), TensorShape([180, 180, 3]))

In [6]:
tf.image.ssim(sample2, sample2, 255)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [7]:
sample1 = tf.expand_dims(sample1, axis=0)
sample2 = tf.expand_dims(sample2, axis=0)
sample1.shape, sample2.shape

(TensorShape([1, 180, 180, 3]), TensorShape([1, 180, 180, 3]))

In [8]:
1 - tf.image.ssim(sample1, sample2, 255)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.90494573], dtype=float32)>

In [9]:
tf.image.ssim(sample1, sample2, 255)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.09505427], dtype=float32)>

In [10]:
|

SyntaxError: invalid syntax (Temp/ipykernel_11412/525519296.py, line 1)