In [1]:
import tensorflow as tf
from tensorflow import keras
import tensorflow_datasets as tfds

In [2]:
(train_ds, val_ds, test_ds), metadata = tfds.load(
    'tf_flowers',
    split=['train[:80%]', 'train[80%:90%]', 'train[90%:]'],
    with_info=True,
    as_supervised=True,
)

In [6]:
for i, (x_batch, y_batch) in enumerate(train_ds):
    print(i, x_batch)

0 tf.Tensor(
[[[ 93 122  30]
  [ 90 118  31]
  [ 88 118  28]
  ...
  [247  77  78]
  [253  87  87]
  [255  76  75]]

 [[ 98 125  30]
  [ 95 124  32]
  [ 96 125  32]
  ...
  [247  81  83]
  [250  86  84]
  [252  71  64]]

 [[ 98 126  26]
  [101 128  31]
  [106 132  33]
  ...
  [254  81  85]
  [254  79  76]
  [252  55  47]]

 ...

 [[ 35  51   6]
  [ 21  49   0]
  [ 30  57   6]
  ...
  [224 239  78]
  [192 208  50]
  [ 88  54  53]]

 [[ 65  73  32]
  [ 20  46   0]
  [ 22  48   0]
  ...
  [230 236  74]
  [230 246  62]
  [ 88  57  36]]

 [[ 95  97  60]
  [ 15  41   0]
  [ 23  51   3]
  ...
  [210 224  40]
  [210 241  23]
  [ 93  87  11]]], shape=(333, 500, 3), dtype=uint8)
1 tf.Tensor(
[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [ 75 107 145]
  [ 75 109 146]
  [ 75 111 147]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [ 75 107 145]
  [ 75 109 146]
  [ 75 111 147]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [ 75 107 145]
  [ 75 109 146]
  [ 76 110 147]

375 tf.Tensor(
[[[100 110 109]
  [110 124 127]
  [121 135 136]
  ...
  [ 12  25  18]
  [  7  17  16]
  [  7  17  18]]

 [[ 98 118 106]
  [126 134 157]
  [124 128 137]
  ...
  [ 12  23  17]
  [  5  15  14]
  [  6  14  16]]

 [[111 130 136]
  [121 129 142]
  [112 110 124]
  ...
  [ 11  22  18]
  [  9  18  15]
  [ 10  19  18]]

 ...

 [[ 77 105  56]
  [ 80 111  69]
  [ 69  82  38]
  ...
  [ 38  78  28]
  [ 22  52  16]
  [ 21  44  15]]

 [[125 139  88]
  [ 58  86  46]
  [ 67  96  50]
  ...
  [ 37  76  32]
  [ 17  42  10]
  [ 32  48  19]]

 [[155 180 114]
  [112 119  78]
  [ 71 104  51]
  ...
  [ 55  93  46]
  [ 28  51   7]
  [ 58  72  23]]], shape=(333, 500, 3), dtype=uint8)
376 tf.Tensor(
[[[  0  37   0]
  [  0  38   0]
  [  0  40   0]
  ...
  [ 79 149  14]
  [ 82 150  15]
  [ 83 149  15]]

 [[  0  37   0]
  [  0  38   0]
  [  0  40   0]
  ...
  [ 79 149  14]
  [ 81 148  16]
  [ 80 147  15]]

 [[  1  37   1]
  [  1  39   0]
  [  0  41   1]
  ...
  [ 80 147  15]
  [ 79 146  14]
  [ 79 146 

  [  5  45  45]]], shape=(213, 320, 3), dtype=uint8)
690 tf.Tensor(
[[[ 59 112 180]
  [ 60 113 181]
  [ 61 114 180]
  ...
  [ 42 100 174]
  [ 41  99 173]
  [ 41  99 173]]

 [[ 59 112 180]
  [ 60 113 181]
  [ 62 115 181]
  ...
  [ 42 100 174]
  [ 41  99 173]
  [ 41  99 173]]

 [[ 61 114 182]
  [ 60 115 182]
  [ 61 116 181]
  ...
  [ 42 100 174]
  [ 42 100 174]
  [ 42 100 174]]

 ...

 [[ 47  68   9]
  [ 51  71  12]
  [ 55  74  18]
  ...
  [ 20  31   0]
  [ 17  28   0]
  [ 18  29   0]]

 [[ 49  71   9]
  [ 51  73  11]
  [ 54  74  15]
  ...
  [ 17  31   0]
  [ 15  28   0]
  [ 17  30   2]]

 [[ 50  75  10]
  [ 52  74  12]
  [ 52  73  14]
  ...
  [ 15  30   0]
  [ 15  28   0]
  [ 17  30   2]]], shape=(215, 240, 3), dtype=uint8)
691 tf.Tensor(
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 2

989 tf.Tensor(
[[[119  10  15]
  [121  12  17]
  [126  16  19]
  ...
  [169  29  38]
  [174  34  43]
  [175  34  43]]

 [[118   9  14]
  [119  10  15]
  [125  15  18]
  ...
  [169  30  37]
  [173  32  41]
  [174  33  42]]

 [[117   8  13]
  [118   9  14]
  [123  13  16]
  ...
  [172  31  39]
  [176  35  44]
  [178  34  44]]

 ...

 [[164  79 102]
  [159  77 100]
  [154  76  98]
  ...
  [114  42  30]
  [120  41  34]
  [120  39  36]]

 [[168  83 106]
  [165  81 104]
  [162  80 103]
  ...
  [122  37  34]
  [127  37  37]
  [128  36  39]]

 [[172  84 108]
  [169  84 107]
  [167  83 107]
  ...
  [123  33  33]
  [126  34  37]
  [130  35  43]]], shape=(333, 500, 3), dtype=uint8)
990 tf.Tensor(
[[[ 6 12  0]
  [10 16  2]
  [ 7 13  0]
  ...
  [ 0  2  0]
  [ 2  2  0]
  [ 0  0  0]]

 [[ 7 13  0]
  [ 7 15  0]
  [ 6 14  0]
  ...
  [ 1  1  1]
  [ 1  1  1]
  [ 1  0  0]]

 [[ 8 16  1]
  [ 6 14  0]
  [ 6 17  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 1  0  0]]

 ...

 [[ 0  6  0]
  [ 0  7  0]
  [ 2 12  4]
  

1282 tf.Tensor(
[[[105  99  75]
  [106 100  78]
  [106 100  78]
  ...
  [148 145 114]
  [147 144 113]
  [146 143 112]]

 [[109 101  80]
  [105  99  77]
  [104  97  78]
  ...
  [148 143 113]
  [147 142 112]
  [146 141 111]]

 [[111 103  84]
  [109 101  82]
  [106  99  81]
  ...
  [146 141 111]
  [145 140 110]
  [145 140 110]]

 ...

 [[ 96  80  57]
  [ 98  82  59]
  [ 94  78  55]
  ...
  [190 188 150]
  [191 189 151]
  [186 184 146]]

 [[ 97  90  72]
  [100  91  74]
  [103  94  77]
  ...
  [216 223 171]
  [222 227 173]
  [220 225 171]]

 [[ 54  51  42]
  [ 57  53  42]
  [ 58  54  43]
  ...
  [107 107  97]
  [110 110 100]
  [106 106  96]]], shape=(281, 500, 3), dtype=uint8)
1283 tf.Tensor(
[[[ 83  93   0]
  [ 93  98  44]
  [ 36  34  22]
  ...
  [238 241 246]
  [237 240 245]
  [237 240 245]]

 [[105 115  16]
  [ 52  53  21]
  [ 35  40   0]
  ...
  [240 243 248]
  [240 243 248]
  [240 243 248]]

 [[107 115  29]
  [ 62  67  11]
  [ 80  90  19]
  ...
  [242 245 250]
  [242 245 250]
  [243 24

1607 tf.Tensor(
[[[0 6 0]
  [0 6 0]
  [0 6 0]
  ...
  [0 5 0]
  [0 6 0]
  [0 6 0]]

 [[0 6 0]
  [0 6 0]
  [0 6 0]
  ...
  [0 5 0]
  [0 6 0]
  [0 6 0]]

 [[0 6 0]
  [0 6 0]
  [0 6 0]
  ...
  [0 5 0]
  [0 6 0]
  [0 6 0]]

 ...

 [[0 5 0]
  [0 5 0]
  [0 5 0]
  ...
  [0 2 0]
  [0 2 0]
  [0 2 0]]

 [[0 4 0]
  [0 4 0]
  [0 4 0]
  ...
  [0 2 0]
  [0 2 0]
  [0 2 0]]

 [[0 4 0]
  [0 4 0]
  [0 4 0]
  ...
  [0 2 0]
  [0 2 0]
  [1 3 0]]], shape=(213, 320, 3), dtype=uint8)
1608 tf.Tensor(
[[[  6   2   0]
  [  7   4   0]
  [ 10   7   2]
  ...
  [  3   4   0]
  [  0   1   0]
  [  4   0   0]]

 [[ 12   8   5]
  [ 12   9   4]
  [ 13  10   5]
  ...
  [ 16  13   8]
  [  9   8   3]
  [ 10   6   3]]

 [[ 13   9   6]
  [ 14  11   6]
  [ 15  12   7]
  ...
  [ 37  30  24]
  [ 30  25  19]
  [ 25  17  14]]

 ...

 [[ 44  33  27]
  [ 71  60  54]
  [ 54  43  37]
  ...
  [ 48  55  39]
  [ 18  27  24]
  [  0   0   4]]

 [[ 54  45  40]
  [ 71  62  57]
  [ 54  47  41]
  ...
  [ 27  27   0]
  [ 14  14   2]
  [ 40  53 

1921 tf.Tensor(
[[[33 45 21]
  [32 44 20]
  [33 43 19]
  ...
  [44 54 29]
  [43 53 28]
  [43 53 28]]

 [[35 45 21]
  [34 44 20]
  [33 43 19]
  ...
  [44 54 29]
  [43 53 28]
  [42 52 27]]

 [[35 43 20]
  [35 43 20]
  [34 42 19]
  ...
  [43 53 28]
  [43 53 28]
  [42 52 27]]

 ...

 [[43 60  6]
  [47 64  9]
  [51 71 12]
  ...
  [20 30  6]
  [20 30  6]
  [20 30  6]]

 [[43 60  6]
  [48 65 10]
  [52 70 12]
  ...
  [20 28  5]
  [20 28  5]
  [20 28  5]]

 [[44 58  7]
  [49 64  7]
  [53 69  6]
  ...
  [20 29  8]
  [19 28  7]
  [18 27  6]]], shape=(241, 320, 3), dtype=uint8)
1922 tf.Tensor(
[[[160 187 204]
  [158 187 205]
  [155 186 206]
  ...
  [  0  24 174]
  [  0  26 175]
  [  0  26 175]]

 [[160 187 204]
  [156 187 205]
  [155 186 206]
  ...
  [  1  25 175]
  [  0  25 174]
  [  0  25 174]]

 [[160 187 204]
  [156 187 205]
  [154 185 205]
  ...
  [  1  27 174]
  [  0  27 176]
  [  0  27 176]]

 ...

 [[ 76 123  31]
  [126 169  62]
  [162 195  82]
  ...
  [ 85 114   8]
  [ 52 106   0]
  [ 58 

2263 tf.Tensor(
[[[184 191 201]
  [186 190 201]
  [188 190 202]
  ...
  [193 201 212]
  [192 200 211]
  [191 201 213]]

 [[184 191 201]
  [186 190 201]
  [187 189 201]
  ...
  [195 204 213]
  [193 203 213]
  [193 203 213]]

 [[183 190 200]
  [186 190 201]
  [187 189 201]
  ...
  [194 203 212]
  [194 202 213]
  [192 202 212]]

 ...

 [[ 37  42  19]
  [ 37  47  23]
  [ 42  52  27]
  ...
  [ 67  77  42]
  [ 69  76  43]
  [ 67  71  46]]

 [[ 38  43  21]
  [ 38  48  23]
  [ 44  54  27]
  ...
  [ 69  81  45]
  [ 70  79  48]
  [ 68  73  50]]

 [[ 37  42  20]
  [ 38  48  21]
  [ 42  55  25]
  ...
  [ 72  82  47]
  [ 74  81  48]
  [ 70  75  52]]], shape=(333, 500, 3), dtype=uint8)
2264 tf.Tensor(
[[[ 66  70  56]
  [ 68  72  58]
  [ 69  73  59]
  ...
  [ 77  89  65]
  [ 78  91  65]
  [ 77  91  65]]

 [[ 68  72  57]
  [ 64  73  56]
  [ 62  71  54]
  ...
  [ 76  90  65]
  [ 76  90  65]
  [ 76  90  64]]

 [[ 65  69  52]
  [ 61  73  53]
  [ 61  74  56]
  ...
  [ 76  90  65]
  [ 75  89  64]
  [ 75  8

2599 tf.Tensor(
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]], shape=(246, 320, 3), dtype=uint8)
2600 tf.Tensor(
[[[246 240 224]
  [246 241 222]
  [246 241 222]
  ...
  [209 186 110]
  [212 186 111]
  [212 186 109]]

 [[246 241 222]
  [246 241 222]
  [246 241 222]
  ...
  [212 188 114]
  [214 188 113]
  [214 188 113]]

 [[247 242 223]
  [246 241 222]
  [246 241 222]
  ...
  [214 188 114]
  [214 188 114]
  [214 18

  [ 57 106 175]]], shape=(331, 500, 3), dtype=uint8)
2918 tf.Tensor(
[[[103 145  69]
  [104 146  70]
  [104 146  70]
  ...
  [ 21  24  17]
  [ 21  24  17]
  [ 21  24  17]]

 [[103 145  69]
  [104 146  70]
  [104 146  70]
  ...
  [ 23  24  18]
  [ 23  24  18]
  [ 23  24  18]]

 [[104 146  70]
  [104 146  70]
  [104 146  70]
  ...
  [ 22  23  17]
  [ 22  23  17]
  [ 22  23  17]]

 ...

 [[131 160  93]
  [131 160  93]
  [131 160  93]
  ...
  [237 110  91]
  [240 111  89]
  [240 112  85]]

 [[130 159  92]
  [130 159  92]
  [130 159  92]
  ...
  [236 109  90]
  [239 110  88]
  [239 111  86]]

 [[130 159  93]
  [130 159  93]
  [130 159  93]
  ...
  [235 108  91]
  [237 108  87]
  [238 109  87]]], shape=(333, 500, 3), dtype=uint8)
2919 tf.Tensor(
[[[219 184   4]
  [124  79  12]
  [121  85   0]
  ...
  [103 125  61]
  [158 137  44]
  [179 143   5]]

 [[195 151   0]
  [156 115   0]
  [136  97   4]
  ...
  [ 86  90  53]
  [117 126  71]
  [155 125  61]]

 [[244 204  11]
  [226 193   0]
  [222 193

In [3]:
samples = []
for data in train_ds.take(2):
    samples.append(data[0])

In [4]:
samples[0].shape, samples[1].shape

(TensorShape([333, 500, 3]), TensorShape([212, 320, 3]))

In [5]:
sample1 = tf.image.resize(samples[0], [180, 180])
sample2 = tf.image.resize(samples[1], [180, 180])
sample1.shape, sample2.shape

(TensorShape([180, 180, 3]), TensorShape([180, 180, 3]))

In [6]:
tf.image.ssim(sample2, sample2, 255)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [7]:
sample1 = tf.expand_dims(sample1, axis=0)
sample2 = tf.expand_dims(sample2, axis=0)
sample1.shape, sample2.shape

(TensorShape([1, 180, 180, 3]), TensorShape([1, 180, 180, 3]))

In [8]:
1 - tf.image.ssim(sample1, sample2, 255)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.90494573], dtype=float32)>

In [9]:
tf.image.ssim(sample1, sample2, 255)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.09505427], dtype=float32)>

In [10]:
|

SyntaxError: invalid syntax (Temp/ipykernel_11412/525519296.py, line 1)