In [1]:
import tensorflow as tf
from tensorflow.keras.utils import plot_model
import resnet_V2
import inverse_mobilenet
from tensorflow import keras
import data_util

(None, 128, 128, 16)


In [2]:
temp = keras.applications.MobileNetV2(input_shape=(256, 256, 3), alpha=1.0, include_top=False, weights=None)
temp.summary()

Model: "mobilenetv2_1.00_256"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 256, 256, 3) 0                                            
__________________________________________________________________________________________________
Conv1_pad (ZeroPadding2D)       (None, 257, 257, 3)  0           input_2[0][0]                    
__________________________________________________________________________________________________
Conv1 (Conv2D)                  (None, 128, 128, 32) 864         Conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_Conv1 (BatchNormalization)   (None, 128, 128, 32) 128         Conv1[0][0]                      
_______________________________________________________________________________

In [2]:
ae = resnet_V2.ResNetAE(drop_out=None)
mae = inverse_mobilenet.MobileNetAE((256, 256, 3), 99)

In [3]:
train_ds = data_util.get_autoencoder_dataset(batch_size=16)
sample = None
for t in train_ds.take(1):
    sample = t
sample.shape

TensorShape([16, 256, 256, 3])

In [4]:
sample

<tf.Tensor: shape=(16, 256, 256, 3), dtype=float32, numpy=
array([[[[0.61681986, 0.61228555, 0.1984375 ],
         [0.6347273 , 0.62688416, 0.22418812],
         [0.65410537, 0.6452359 , 0.2571385 ],
         ...,
         [0.88563114, 0.84984684, 0.49396446],
         [0.94165134, 0.9063572 , 0.54067093],
         [0.93998164, 0.9086091 , 0.52429533]],

        [[0.7017004 , 0.69385725, 0.29361212],
         [0.720481  , 0.7110294 , 0.3216146 ],
         [0.67956495, 0.66780025, 0.29160538],
         ...,
         [0.9359069 , 0.9040288 , 0.54791665],
         [0.9924326 , 0.9723039 , 0.60638785],
         [0.97734374, 0.954473  , 0.5701593 ]],

        [[0.7757047 , 0.7647978 , 0.38097426],
         [0.6860754 , 0.6744179 , 0.2998315 ],
         [0.75548404, 0.7433364 , 0.37768075],
         ...,
         [0.9273131 , 0.9059896 , 0.5465533 ],
         [0.9953125 , 0.99313724, 0.6292586 ],
         [0.9532782 , 0.93812805, 0.5545803 ]],

        ...,

        [[0.64587927, 0.5316636 ,

In [5]:
ae_out = mae(sample)
ae_out

<tf.Tensor: shape=(16, 256, 256, 3), dtype=float32, numpy=
array([[[[0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5],
         ...,
         [0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5]],

        [[0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5],
         ...,
         [0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5]],

        [[0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5],
         ...,
         [0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5]],

        ...,

        [[0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5],
         ...,
         [0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5]],

        [[0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5],
         ...,
         [0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5]],

        [[0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5],
         [0.5, 

In [6]:
mae = keras.losses.MeanAbsoluteError()
mae(sample, ae_out)

<tf.Tensor: shape=(), dtype=float32, numpy=0.24118505>